Vagrant.configure("2") do |config|
  config.vm.box = "codecool/ubuntu-18.04-base"

  config.vm.define "db", autostart: false do |db|
    db.vm.hostname = 'db'
    db.vm.provision "shell", path: "db.sh"
    db.vm.network "forwarded_port", guest: 5432, host: 5432
  end

  config.vm.define "web1", autostart: false do |web|
    web.vm.hostname = 'web1'
    web.vm.provision "shell", path: "web.sh"
    web.vm.provision "shell", path: "web1.sh"
    web.vm.network "forwarded_port", guest: 8080, host: 8080
    web.vm.network "forwarded_port", guest: 5432, host: 5432
  end

  config.vm.define "web2", autostart: false do |web|
    web.vm.hostname = 'web2'
    web.vm.provision "shell", path: "web.sh"
    web.vm.provision "shell", path: "web2.sh"
    web.vm.network "forwarded_port", guest: 8080, host: 8080
    web.vm.network "forwarded_port", guest: 5432, host: 5432
  end

  config.vm.define "web3", autostart: false do |web|
    web.vm.hostname = 'web3'
    web.vm.provision "shell", path: "web.sh"
    web.vm.provision "shell", path: "web3.sh"
    web.vm.network "forwarded_port", guest: 8080, host: 8080
    web.vm.network "forwarded_port", guest: 5432, host: 5432
  end
end
