version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: vagrant
      MYSQL_DATABASE: db
      MYSQL_USER: vagrant
      MYSQL_PASSWORD: vagrant 
  wp1:
    image: wordpress:5.6
    volumes:
      - wp1_data:/var/www/html
    restart: always
    ports:
      - "8000:80"
      - "3306:3306"
    environment: 
      WORDPRESS_DB_HOST: 84.236.23.162:3306
      WORDPRESS_DB_USER: vagrant
      WORDPRESS_DB_PASSWORD: vagrant
      WORDPRESS_DB_NAME: db
      WORDPRESS_CONFIG_EXTRA: |-
        define('WP_HOME', 'http://localhost:8000');
        define('WP_SITEURL', 'http://localhost:8000');

  wp2:
    image: wordpress:5.6
    volumes:
      - wp2_data:/var/www/html
    restart: always
    ports:
      - "8000:80"
      - "3306:3306"
    environment: 
      WORDPRESS_DB_HOST: 31.24.19.80:3306
      WORDPRESS_DB_USER: vagrant
      WORDPRESS_DB_PASSWORD: vagrant
      WORDPRESS_DB_NAME: db
      WORDPRESS_CONFIG_EXTRA: |-
                              define('WP_HOME', 'http://localhost:8000');
                              define('WP_SITEURL', 'http://localhost:8000');
  wp3:
    image: wordpress:5.6
    volumes:
      - wp3_data:/var/www/html
    restart: always
    ports:
      - "8000:80"
      - "3306:3306"
    environment: 
      WORDPRESS_DB_HOST: 94.21.62.200:3306
      WORDPRESS_DB_USER: vagrant
      WORDPRESS_DB_PASSWORD: vagrant
      WORDPRESS_DB_NAME: db
      WORDPRESS_CONFIG_EXTRA: |-
                              define('WP_HOME', 'http://localhost:8000');
                              define('WP_SITEURL', 'http://localhost:8000');

volumes:
  db_data:
  wp1_data:
  wp2_data:
  wp3_data:
